export interface ProjectConfig {
  project_id: string;
  platform: 'web' | 'mobile_web' | 'pwa' | 'desktop_web';
  framework: 'nextjs' | 'react' | 'vue' | 'svelte' | 'angular' | 'vanilla' | 'nuxt' | 'remix';
  base_url: string;
  selector_strategy?: SelectorStrategy;
  auth?: AuthConfig;
  flows?: FlowConfig[];
  tiers?: TierConfig;
  docs?: Record<string, string>;
  locale?: LocaleConfig;
  alert_routes?: Record<string, string>;
  destructive_commands?: string[];
  safety_notes?: string[];
  quirks?: string[];
  ai_fallback?: AIFallbackConfig;
  environments?: Record<string, EnvironmentConfig>;
  visual_baseline?: VisualBaselineConfig;
  performance_budget?: PerformanceBudgetConfig;
  parallelization?: ParallelizationConfig;
  notifications?: NotificationConfig;
}

export interface TierConfig {
  static?: string[];
  smoke?: string[];
  smoke_url_flag?: string;
  worker?: string[];
  worker_optional?: string[];
  extra_services?: ExtraServiceTier[];
}

export interface ExtraServiceTier {
  id: string;
  name?: string;
  commands: string[];
}

export interface LocaleConfig {
  default?: string;
  toggle?: boolean;
  viewport_min?: number;
  viewport_max?: number;
}

export interface SelectorStrategy {
  primary: 'data-testid' | 'aria' | 'testid' | 'id';
  fallback_chain: Array<'data-testid' | 'aria' | 'text' | 'css' | 'xpath' | 'visual' | 'position'>;
  conventions?: Record<string, any>;
}

export interface AuthConfig {
  type: 'cookie_session' | 'jwt_header' | 'jwt_cookie' | 'oauth' | 'basic' | 'none';
  login_flow?: string;
  test_credentials?: {
    email?: string;
    password?: string;
    username?: string;
    otp_secret?: string;
  };
  token_storage?: 'cookie' | 'localStorage' | 'sessionStorage' | 'memory';
}

export interface FlowConfig {
  id: string;
  name?: string;
  path: string[];
  checks?: string[];
  critical?: boolean;
  revenue_impact?: 'none' | 'low' | 'medium' | 'high' | 'critical';
  data_driven?: boolean;
}

export interface AIFallbackConfig {
  enabled: boolean;
  trigger?: 'selector_failure' | 'healing_exhausted' | 'manual';
  vision_provider?: 'opencli' | 'kimi' | 'browser-use';
  rate_limit?: number;
}

export interface EnvironmentConfig {
  api_base?: string;
  database_snapshot?: string;
  read_only?: boolean;
  notes?: string;
  required_env?: string[];
}

export interface VisualBaselineConfig {
  max_diff_pixels?: number;
  threshold?: number;
  mask_selectors?: string[];
}

export interface PerformanceBudgetConfig {
  lighthouse_score?: number;
  first_contentful_paint?: number;
  largest_contentful_paint?: number;
  time_to_interactive?: number;
}

export interface ParallelizationConfig {
  shards?: number;
  workers?: number;
}

export interface NotificationConfig {
  slack_webhook?: string;
  email?: string;
  pagerduty_key?: string;
}

export interface Selector {
  type: 'data-testid' | 'aria' | 'text' | 'css' | 'xpath' | 'visual' | 'position';
  value: string;
  context?: string;
  weight: number;
}

export interface SelectorChain {
  primary: Selector;
  fallbacks: Selector[];
  healingHistory: HealingEvent[];
  confidenceScore: number;
}

export interface HealingEvent {
  timestamp: Date;
  failedSelector: Selector;
  healedSelector: Selector;
  similarityScore: number;
  testId: string;
  autoApplied: boolean;
}

export interface DiscoveredFlow {
  id: string;
  path: string[];
  source: 'git-diff' | 'router' | 'traffic' | 'manual';
  confidence: number;
  critical?: boolean;
  frequency?: number;
  isDynamic?: boolean;
  parameters?: string[];
  hasForm?: boolean;
  sources?: string[];
}

export interface GeneratedTest {
  id: string;
  name: string;
  flowId: string;
  priority: string;
  steps: TestStep[];
  source: string;
  autoGenerated: boolean;
  version: number;
}

export interface TestStep {
  action: string;
  target: Selector;
  value?: string;
  assertions: Assertion[];
}

export interface Assertion {
  type: string;
  expected?: string | RegExp;
  selector?: string;
  state?: string;
  baseline?: string;
}

export interface TestResult {
  testId: string;
  runId: string;
  status: 'passed' | 'failed' | 'flaky' | 'skipped' | 'healed';
  durationMs: number;
  failureType?: string;
  healingEvents?: HealingEvent[];
  screenshots: string[];
  traces: string[];
  apiLogs: string[];
}

export interface Route {
  path: string;
  isDynamic: boolean;
  parameters?: string[];
  component?: string;
}

export interface ComponentNode {
  name: string;
  selector: string;
  children: ComponentNode[];
  props?: Record<string, unknown>;
}

export interface ElementLocation {
  x: number;
  y: number;
  width: number;
  height: number;
  confidence: number;
}
