#!/usr/bin/env node
/**
 * Generate Playwright test skeleton from uat-manifest.yml flows[].
 *
 * Usage:
 *   node codegen.mjs [--manifest path] [--out dir] [projectRoot]
 *
 * Writes .uat/generated/flows.spec.ts (or --out path). Does not overwrite without --force.
 */
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function parseArgs(argv) {
  const out = { manifest: null, root: process.cwd(), outDir: null, force: false };
  for (let i = 2; i < argv.length; i++) {
    if (argv[i] === '--manifest' && argv[i + 1]) out.manifest = argv[++i];
    else if (argv[i] === '--out' && argv[i + 1]) out.outDir = argv[++i];
    else if (argv[i] === '--force') out.force = true;
    else if (!argv[i].startsWith('--')) out.root = argv[i];
  }
  out.root = path.resolve(out.root);
  out.manifest = out.manifest
    ? path.resolve(out.manifest)
    : path.join(out.root, 'uat-manifest.yml');
  out.outDir = out.outDir ? path.resolve(out.outDir) : path.join(out.root, '.uat', 'generated');
  return out;
}

function loadFlows(manifestPath) {
  const reader = path.join(__dirname, 'lib', 'read-manifest.mjs');
  const r = spawnSync(process.execPath, [reader, manifestPath, 'flows-json'], { encoding: 'utf8' });
  if (r.status !== 0) return null;
  try {
    return JSON.parse(r.stdout);
  } catch {
    return null;
  }
}

function escapeStr(s) {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function generateSpec(doc) {
  const baseUrl = doc.base_url || 'http://127.0.0.1:3000';
  const lines = [
    '// Generated by uat-harness-skill codegen.mjs — review and customize before CI.',
    "import { test, expect } from '@playwright/test';",
    '',
    `const BASE_URL = process.env.UAT_URL || '${escapeStr(baseUrl)}';`,
    '',
  ];

  for (const flow of doc.flows || []) {
    const route = (flow.path && flow.path[0]) || '/';
    const urlPath = route.startsWith('/') ? route : `/${route}`;
    const title = flow.name || flow.id;
    lines.push(`test.describe('${escapeStr(flow.id)} — ${escapeStr(title)}', () => {`);
    lines.push(`  test('walkthrough', async ({ page }) => {`);
    lines.push(`    await page.goto(\`\${BASE_URL}${urlPath}\`);`);
    lines.push(`    await expect(page).toHaveURL(new RegExp('${escapeStr(route.replace(/^\//, '')) || ''}'));`);
    for (const check of flow.checks || []) {
      lines.push(`    // CHECK: ${check}`);
    }
    lines.push('  });');
    lines.push('});');
    lines.push('');
  }

  return lines.join('\n');
}

function main() {
  const opts = parseArgs(process.argv);
  if (!fs.existsSync(opts.manifest)) {
    console.error(`No manifest at ${opts.manifest}. Run init first.`);
    process.exit(1);
  }

  const doc = loadFlows(opts.manifest);
  if (!doc?.flows?.length) {
    console.error('No flows[] in manifest.');
    process.exit(1);
  }

  fs.mkdirSync(opts.outDir, { recursive: true });
  const outFile = path.join(opts.outDir, 'flows.spec.ts');
  if (fs.existsSync(outFile) && !opts.force) {
    console.error(`Already exists: ${outFile} (use --force to overwrite)`);
    process.exit(1);
  }

  const spec = generateSpec(doc);
  fs.writeFileSync(outFile, spec, 'utf8');
  console.log(`Wrote ${outFile}`);
  console.log('Run: npx playwright test .uat/generated/flows.spec.ts');
}

main();
