#!/usr/bin/env node
/**
 * One-command UAT setup for consumer projects.
 *
 * What it does:
 * 1) Scaffolds uat-manifest.yml when missing (or with --refresh)
 * 2) Wires uat:* npm scripts into package.json idempotently
 * 3) Lets user choose local/preview/custom base URL
 * 4) Runs an audit summary at the end (unless --dry-run)
 *
 * Usage:
 *   node setup.mjs [--yes] [--dry-run] [--env local|preview|custom] [--url https://...]
 *                  [--manifest /path/to/uat-manifest.yml] [--refresh] [projectRoot]
 */
import fs from 'node:fs';
import path from 'node:path';
import readline from 'node:readline/promises';
import { spawnSync } from 'node:child_process';
import { stdin as input, stdout as output } from 'node:process';
import { fileURLToPath } from 'node:url';
import { discoverAll, draftSuggestions } from './discover.mjs';
import { findProjectDocs } from './lib/tailor-helpers.mjs';
import { printBanner } from './lib/banner.mjs';
import { assessProjectHealth, formatHealthPretty } from './lib/health.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function parseArgs(argv) {
  const out = {
    yes: false,
    dryRun: false,
    refresh: false,
    env: '',
    url: '',
    manifest: '',
    root: process.cwd(),
  };
  for (let i = 2; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--yes' || a === '-y') out.yes = true;
    else if (a === '--dry-run') out.dryRun = true;
    else if (a === '--refresh') out.refresh = true;
    else if (a === '--env' && argv[i + 1]) out.env = argv[++i].trim().toLowerCase();
    else if (a === '--url' && argv[i + 1]) out.url = argv[++i].trim();
    else if (a === '--manifest' && argv[i + 1]) out.manifest = argv[++i].trim();
    else if (!a.startsWith('--')) out.root = a;
  }
  out.root = path.resolve(out.root);
  out.manifest = out.manifest ? path.resolve(out.manifest) : path.join(out.root, 'uat-manifest.yml');
  if (out.env && !['local', 'preview', 'custom'].includes(out.env)) {
    throw new Error(`Invalid --env "${out.env}". Use one of: local, preview, custom.`);
  }
  return out;
}

function slug(value) {
  return (value || 'project')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '') || 'project';
}

function detectProjectId(root) {
  const pkgPath = path.join(root, 'package.json');
  if (fs.existsSync(pkgPath)) {
    try {
      const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
      if (pkg.name) return slug(pkg.name);
    } catch {
      /* ignore */
    }
  }
  return slug(path.basename(root));
}

function detectFramework(discovery) {
  return discovery.projects?.[0]?.framework || 'unknown';
}

function normalizeUrl(url) {
  if (!url) return '';
  return url.replace(/\/+$/, '');
}

function isValidHttpUrl(url) {
  try {
    const u = new URL(url);
    return u.protocol === 'http:' || u.protocol === 'https:';
  } catch {
    return false;
  }
}

function yamlScalar(value) {
  if (value === null || value === undefined) return "''";
  const s = String(value);
  return `'${s.replace(/'/g, "''")}'`;
}

async function chooseBaseUrl(opts, hasInteractivePrompt) {
  if (opts.url) {
    const normalized = normalizeUrl(opts.url);
    if (!isValidHttpUrl(normalized)) {
      throw new Error(`Invalid --url "${opts.url}". Use http:// or https://.`);
    }
    return normalized;
  }
  if (opts.env === 'local') return 'http://127.0.0.1:3000';
  if ((opts.env === 'preview' || opts.env === 'custom') && (opts.yes || !hasInteractivePrompt)) {
    throw new Error(`--env ${opts.env} requires --url in non-interactive mode.`);
  }
  if (opts.yes || !hasInteractivePrompt) return 'http://127.0.0.1:3000';

  const rl = readline.createInterface({ input, output });
  try {
    const modeRaw = await rl.question(
      'Choose target environment [1=local localhost, 2=preview URL, 3=custom URL] (default 1): '
    );
    const mode = (modeRaw || '1').trim();
    if (mode === '2' || mode === '3') {
      const url = await rl.question('Enter URL (e.g. https://preview.example.com): ');
      const normalized = normalizeUrl(url.trim());
      if (normalized && isValidHttpUrl(normalized)) return normalized;
      console.log('Invalid URL, falling back to local http://127.0.0.1:3000');
    }
    return 'http://127.0.0.1:3000';
  } finally {
    rl.close();
  }
}

function renderManifestYaml(doc) {
  const lines = [];
  lines.push('# Generated by uat-harness-skill setup.mjs. Review before commit.');
  lines.push('# Next: run `npm run uat:tailor` — agent customizes flows for THIS project.');
  lines.push(`project_id: ${yamlScalar(doc.project_id)}`);
  lines.push(`platform: ${yamlScalar(doc.platform)}`);
  lines.push(`framework: ${yamlScalar(doc.framework)}`);
  lines.push(`base_url: ${yamlScalar(doc.base_url)}`);
  lines.push('');
  lines.push('preflight:');
  lines.push(`  health_path: ${yamlScalar(doc.preflight.health_path)}`);
  lines.push('');
  lines.push('docs:');
  lines.push(`  uat: ${yamlScalar('UAT.md')}`);
  if (doc.docs?.userflow) {
    lines.push(`  userflow: ${yamlScalar(doc.docs.userflow)}`);
  }
  lines.push('');
  lines.push('# Agent: fill after reading project docs (reference/tailor.md)');
  lines.push('project_context:');
  lines.push(`  audience: ${yamlScalar('(who runs UAT — fill via tailor)')}`);
  lines.push(`  product_surface: ${yamlScalar(doc.project_context?.product_surface || '/')}`);
  lines.push('  critical_journeys: []');
  lines.push('  out_of_scope: []');
  lines.push('');
  lines.push('locale:');
  lines.push('  default: en');
  lines.push('  toggle: false');
  lines.push('  viewport_min: 1280');
  lines.push('  viewport_max: 1440');
  lines.push('');
  lines.push('safety_notes:');
  lines.push('  - Confirm with the user before any destructive_commands');
  lines.push('  - Delete temp screenshots and scratch files after UAT');
  lines.push('');
  lines.push('tiers:');
  lines.push('  static:');
  for (const cmd of doc.tiers.static) lines.push(`    - ${yamlScalar(cmd)}`);
  if (!doc.tiers.static.length) lines.push('    - npm run lint');
  lines.push('  smoke:');
  for (const cmd of doc.tiers.smoke) lines.push(`    - ${yamlScalar(cmd)}`);
  if (!doc.tiers.smoke.length) lines.push('    - npm run smoke-test');
  lines.push(`  smoke_url_flag: ${yamlScalar('--url')}`);
  lines.push('  worker:');
  for (const cmd of doc.tiers.worker) lines.push(`    - ${yamlScalar(cmd)}`);
  if (!doc.tiers.worker.length) lines.push('    - npm run worker:health');
  lines.push('  worker_optional: []');
  lines.push('  extra_services: []');
  lines.push('');
  lines.push('flows:');
  for (const flow of doc.flows) {
    lines.push(`  - id: ${yamlScalar(flow.id)}`);
    lines.push(`    name: ${yamlScalar(flow.name)}`);
    const pathList = (flow.path || []).map((p) => yamlScalar(p)).join(', ');
    lines.push(`    path: [${pathList}]`);
    if (flow.critical) lines.push('    critical: true');
    lines.push('    checks:');
    const checks = flow.checks?.length ? flow.checks : ['page loads without error', 'primary content visible'];
    for (const check of checks) lines.push(`      - ${yamlScalar(check)}`);
  }
  if (!doc.flows.length) {
    lines.push('  - id: home');
    lines.push('    name: Home');
    lines.push('    path: [/]');
    lines.push('    critical: true');
    lines.push('    checks:');
    lines.push('      - primary CTA visible');
    lines.push('      - navigation works');
  }
  lines.push('');
  lines.push('deferred_coverage: []');
  lines.push('');
  lines.push('alert_routes: {}');
  lines.push('');
  lines.push('destructive_commands: []');
  lines.push('');
  lines.push('environments:');
  lines.push('  local:');
  lines.push('    read_only: true');
  lines.push('    required_env: []');
  lines.push('');
  lines.push('auth:');
  lines.push('  type: none');
  lines.push('');
  lines.push('selector_strategy:');
  lines.push('  primary: data-testid');
  lines.push('  fallback_chain: [aria, text]');
  lines.push('');
  return `${lines.join('\n')}\n`;
}

function buildSetupDoc(root, baseUrl, discovery) {
  const draft = draftSuggestions(discovery);
  const docs = findProjectDocs(root);
  const primarySurface =
    discovery.uiRoutes.find((r) => r.path.includes('helloboss'))?.path.split('/').slice(0, 2).join('/') ||
    discovery.uiRoutes.find((r) => r.path !== '/')?.path ||
    '/';
  return {
    project_id: detectProjectId(root),
    platform: 'web',
    framework: detectFramework(discovery),
    base_url: baseUrl,
    preflight: {
      health_path: discovery.apiRoutes.some((r) => /health/i.test(r.path)) ? '/api/health' : '/',
    },
    docs: { userflow: docs.userflow || null },
    project_context: { product_surface: primarySurface === '/' ? '/' : primarySurface },
    tiers: {
      static: draft.tiers.static || [],
      smoke: draft.tiers.smoke || [],
      worker: draft.tiers.worker || [],
    },
    // Seed fewer generic flows — agent must tailor via uat:tailor
    flows: (draft.flows || [])
      .filter((f) => f.path?.[0] === '/' || f.critical)
      .slice(0, 5)
      .map((f, i) => ({
        ...f,
        id: slug(f.id || `flow-${i + 1}`),
        name: String(f.name || f.id || `Flow ${i + 1}`),
        path: (f.path || ['/']).map((p) => String(p || '/')),
        checks: ['(tailor — replace with project-specific checks)'],
      })),
  };
}

function writeManifest(opts, doc) {
  const exists = fs.existsSync(opts.manifest);
  if (exists && !opts.refresh) {
    return { changed: false, reason: 'exists' };
  }
  const yaml = renderManifestYaml(doc);
  if (!opts.dryRun) {
    fs.mkdirSync(path.dirname(opts.manifest), { recursive: true });
    if (exists) {
      const stamp = new Date().toISOString().replace(/[:.]/g, '-');
      fs.copyFileSync(opts.manifest, `${opts.manifest}.${stamp}.bak`);
    }
    fs.writeFileSync(opts.manifest, yaml, 'utf8');
  }
  return { changed: true, reason: exists ? 'refreshed' : 'created', preview: yaml };
}

function wirePackageScripts(root, opts) {
  const pkgPath = path.join(root, 'package.json');
  if (!fs.existsSync(pkgPath)) {
    return { changed: false, reason: 'no-package-json' };
  }

  let pkg;
  try {
    pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
  } catch (err) {
    return { changed: false, reason: 'invalid-package-json', error: err?.message || String(err) };
  }
  const scripts = pkg.scripts || {};
  const desired = {
    'uat:setup': 'node .agents/skills/uat-harness-skill/scripts/setup.mjs --yes',
    'uat:preflight': 'node .agents/skills/uat-harness-skill/scripts/preflight.mjs --pretty',
    'uat:signals': 'node .agents/skills/uat-harness-skill/scripts/context-signals.mjs --pretty',
    'uat:discover': 'node .agents/skills/uat-harness-skill/scripts/discover.mjs --pretty',
    'uat:tailor': 'node .agents/skills/uat-harness-skill/scripts/tailor.mjs --pretty',
    'uat:review': 'node .agents/skills/uat-harness-skill/scripts/review.mjs --pretty',
    'uat:audit': 'node .agents/skills/uat-harness-skill/scripts/audit.mjs --pretty',
    'uat:codegen': 'node .agents/skills/uat-harness-skill/scripts/codegen.mjs --force',
    'uat:tier-a': 'bash .agents/skills/uat-harness-skill/scripts/tier-a.sh',
    'uat:tier-b': 'bash .agents/skills/uat-harness-skill/scripts/tier-b.sh',
    'uat:tier-c': 'bash .agents/skills/uat-harness-skill/scripts/tier-c.sh',
    'uat:tier-d': 'bash .agents/skills/uat-harness-skill/scripts/tier-d.sh',
    'uat:browser': 'bash .agents/skills/uat-harness-skill/scripts/browser.sh',
  };

  let changed = false;
  const conflicts = [];
  for (const [key, cmd] of Object.entries(desired)) {
    if (!scripts[key]) {
      scripts[key] = cmd;
      changed = true;
    } else if (scripts[key] !== cmd) {
      conflicts.push({ key, existing: scripts[key], suggested: cmd });
    }
  }
  pkg.scripts = scripts;
  if (changed && !opts.dryRun) {
    const stamp = new Date().toISOString().replace(/[:.]/g, '-');
    fs.copyFileSync(pkgPath, `${pkgPath}.${stamp}.bak`);
    fs.writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`, 'utf8');
  }
  return { changed, reason: changed ? 'updated' : 'already-present', scripts: desired, conflicts };
}

function runAudit(root) {
  const auditScript = path.join(__dirname, 'audit.mjs');
  const r = spawnSync(process.execPath, [auditScript, '--pretty', root], {
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  });
  return {
    code: r.status ?? 1,
    out: r.stdout || '',
    err: r.stderr || '',
  };
}

async function main() {
  const opts = parseArgs(process.argv);
  if (!fs.existsSync(opts.root)) {
    throw new Error(`Project root does not exist: ${opts.root}`);
  }
  const hasPrompt = process.stdout.isTTY && process.stdin.isTTY;
  const baseUrl = await chooseBaseUrl(opts, hasPrompt);
  const discovery = discoverAll(opts.root);
  const doc = buildSetupDoc(opts.root, baseUrl, discovery);

  printBanner('full');
  console.log(`# UAT setup — ${opts.root}`);
  console.log(`- Base URL: ${baseUrl}`);
  console.log(`- Manifest: ${opts.manifest}`);
  if (opts.dryRun) console.log('- Mode: dry-run (no files changed)');
  console.log('');

  const manifestResult = writeManifest(opts, doc);
  if (manifestResult.reason === 'exists') {
    console.log('manifest: uat-manifest.yml already exists (use --refresh to regenerate).');
  } else {
    console.log(`manifest: ${manifestResult.reason}.`);
  }

  const pkgResult = wirePackageScripts(opts.root, opts);
  if (pkgResult.reason === 'no-package-json') {
    console.log('package.json: not found (skipped npm script wiring).');
  } else if (pkgResult.reason === 'invalid-package-json') {
    console.log(`package.json: invalid JSON (skipped wiring) — ${pkgResult.error}`);
  } else {
    console.log(`package.json: ${pkgResult.reason}.`);
    if (pkgResult.conflicts?.length) {
      console.log('package.json: existing custom uat:* scripts kept (not overwritten):');
      for (const c of pkgResult.conflicts) console.log(`- ${c.key}`);
      console.log('  Use your existing scripts or update manually if needed.');
    }
  }

  if (!opts.dryRun) {
    console.log('');
    const health = assessProjectHealth(opts.root, discovery, doc);
    console.log('Health check:');
    console.log(formatHealthPretty(health));
    console.log('');
    console.log('Next: customize for this project (agent-driven):');
    console.log('  npm run uat:tailor');
    console.log('  → read reference/tailor.md; edit uat-manifest.yml + UAT.md');
    console.log('');
    console.log('Audit snapshot:');
    const audit = runAudit(opts.root);
    if (audit.out) process.stdout.write(audit.out);
    if (audit.code !== 0 && audit.err) process.stderr.write(audit.err);
  } else {
    console.log('');
    console.log('Dry-run next steps:');
    console.log('- Re-run without --dry-run to apply changes.');
    console.log('- Then run: npm run uat:preflight && npm run uat:review');
  }
}

main().catch((err) => {
  console.error(err?.message || err);
  process.exit(1);
});
