import { ProjectConfig, DiscoveredFlow, GeneratedTest, TestStep, Selector, Assertion } from '../core/types';

export class TestGenerator {
  private config: ProjectConfig;

  constructor(config: ProjectConfig) {
    this.config = config;
  }

  async generate(flows: DiscoveredFlow[]): Promise<GeneratedTest[]> {
    const tests: GeneratedTest[] = [];
    for (const flow of flows) {
      const test = await this.generateTest(flow);
      tests.push(test);
    }
    return tests;
  }

  private async generateTest(flow: DiscoveredFlow): Promise<GeneratedTest> {
    const steps: TestStep[] = [];

    if (this.config.auth.type !== 'none') {
      steps.push(this.generateAuthStep());
    }

    for (let i = 0; i < flow.path.length; i++) {
      const path = flow.path[i];
      steps.push(this.generateNavigationStep(path, i === 0));

      if (flow.isDynamic && flow.parameters) {
        steps.push(this.generateDynamicInteraction(path, flow.parameters));
      }
      if (flow.hasForm) {
        steps.push(this.generateFormInteraction(path));
      }
    }

    steps.push(this.generateFinalAssertion(flow));

    return {
      id: `auto-${flow.id}`,
      name: `Flow: ${flow.path.join(' -> ')}`,
      flowId: flow.id,
      priority: this.inferPriority(flow),
      steps,
      source: flow.source,
      autoGenerated: true,
      version: 1,
    };
  }

  private generateAuthStep(): TestStep {
    return {
      action: 'authenticate',
      target: { type: 'data-testid', value: 'login-form', weight: 100 },
      value: JSON.stringify(this.config.auth.test_credentials),
      assertions: [
        { type: 'url', expected: '/dashboard' },
        { type: 'element', selector: '[data-testid="user-menu"]', state: 'visible' },
      ],
    };
  }

  private generateNavigationStep(path: string, isFirst: boolean): TestStep {
    return {
      action: 'navigate',
      target: { type: 'data-testid', value: path, weight: 100 },
      assertions: [
        { type: 'url', expected: path },
        { type: 'load', state: 'networkidle' },
      ],
    };
  }

  private generateDynamicInteraction(path: string, params: string[]): TestStep {
    return {
      action: 'click',
      target: { type: 'css', value: '[data-testid="product-list"] > :first-child', weight: 50 },
      assertions: [
        { type: 'url', expected: new RegExp(path.replace(/:id/, '.*')) },
      ],
    };
  }

  private generateFormInteraction(path: string): TestStep {
    return {
      action: 'fill',
      target: { type: 'css', value: 'form input', weight: 50 },
      value: 'test-data',
      assertions: [
        { type: 'form', state: 'valid' },
      ],
    };
  }

  private generateFinalAssertion(flow: DiscoveredFlow): TestStep {
    return {
      action: 'assert',
      target: { type: 'data-testid', value: 'page-content', weight: 100 },
      assertions: [
        { type: 'element', selector: 'body', state: 'visible' },
      ],
    };
  }

  private inferPriority(flow: DiscoveredFlow): string {
    if (flow.critical) return 'critical';
    if (flow.confidence > 0.8) return 'high';
    if (flow.confidence > 0.5) return 'medium';
    return 'low';
  }
}
